REM INSERTING into EXPORT_TABLE
SET DEFINE OFF;
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('EXPLAINED SQL STATEMENT:');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('------------------------');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('WITH SAWITH0 AS     (SELECT /* + gather_plan_statistics visthak1 */ ');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('T1634475.C320193780 AS c1     FROM       (SELECT ');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('V443943007.NAMED_ACCOUNT_FLAG AS C320193780,         ');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('V451212430.PARTY_ID                 AS C161942247,         ');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('V108392660.PARTY_ID                 AS C296568527,         ');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('V443943007.SALES_ACCOUNT_ID         AS PKA_SalesAccountId0       FROM   ');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('      (SELECT PartyPEO.PARTY_ID         FROM HZ_PARTIES PartyPEO        ');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values (' WHERE ( (1               =1))         AND ( ( (PartyPEO.STATUS = ''A'' ) ');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values (') )         ) V451212430,         (SELECT DISTINCT PUA.party_id         ');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('FROM HZ_PARTY_USG_ASSIGNMENTS PUA         WHERE PUA.status_flag     = ');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('''A''         AND PUA.party_usage_code IN           (SELECT ');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('PUFM.party_usage_code           FROM hz_party_usg_fr_members PUFM       ');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('    WHERE party_usage_fr_id =             (SELECT party_usage_fr_id     ');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('        FROM hz_party_usg_fr_b             WHERE ');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('party_usage_fr_code=''ELIGIBLE_CUSTOMERS''             )           AND ');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('PUFM.party_usage_fr_mem_type     =');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values (' ');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('Plan hash value: 2562969997');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values (' ');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('---------------------------------------------------------------------------------------------------------------------------');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('| Id  | Operation                          | Name                        | E-Rows | Cost (%CPU)|  OMem |  1Mem |  O/1/M   |');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('---------------------------------------------------------------------------------------------------------------------------');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('|   0 | SELECT STATEMENT                   |                             |        |   160K(100)|       |       |          |');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('|   1 |  SORT UNIQUE                       |                             |      2 |   160K  (1)|  2048 |  2048 |     1/0/0|');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('|*  2 |   FILTER                           |                             |        |            |       |       |          |');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('|*  3 |    HASH JOIN OUTER                 |                             |    296K|   152K  (1)|    80M|    10M|     1/0/0|');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('|*  4 |     HASH JOIN                      |                             |    296K| 27815   (3)|    80M|    10M|     1/0/0|');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('|*  5 |      HASH JOIN                     |                             |    296K| 20141   (3)|  1557K|  1557K|     1/0/0|');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('|*  6 |       TABLE ACCESS BY INDEX ROWID  | HZ_PARTY_USG_FR_MEMBERS     |      3 |     2   (0)|       |       |          |');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('|*  7 |        INDEX RANGE SCAN            | HZ_PARTY_USG_FR_MEMBERS_U1  |      3 |     1   (0)|       |       |          |');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('|   8 |         TABLE ACCESS BY INDEX ROWID| HZ_PARTY_USG_FR_B           |      1 |     1   (0)|       |       |          |');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('|*  9 |          INDEX UNIQUE SCAN         | HZ_PARTY_USG_FR_B_U1        |      1 |     0   (0)|       |       |          |');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('|* 10 |       INDEX FAST FULL SCAN         | HZ_PARTY_USG_ASSIGNMENTS_U1 |   3378K| 20095   (3)|       |       |          |');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('|* 11 |      INDEX FAST FULL SCAN          | HZ_PARTIES_N12              |   2778K|  3228   (3)|       |       |          |');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('|  12 |     TABLE ACCESS FULL              | ZCA_SALES_ACCOUNTS          |   2300K|   121K  (1)|       |       |          |');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('---------------------------------------------------------------------------------------------------------------------------');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values (' ');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('Predicate Information (identified by operation id):');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('---------------------------------------------------');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values (' ');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('   2 - filter(CASE "SALESACCOUNTPEO"."NAMED_ACCOUNT_FLAG" WHEN ''Y'' THEN ''NAMED'' ELSE ''NOT_NAMED'' END  IS NOT NULL)');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('   3 - access("PARTYPEO"."PARTY_ID"="SALESACCOUNTPEO"."PARTY_ID")');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('   4 - access("PARTYPEO"."PARTY_ID"="PUA"."PARTY_ID")');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('   5 - access("PUA"."PARTY_USAGE_CODE"="PUFM"."PARTY_USAGE_CODE")');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('   6 - filter(("PUFM"."PARTY_USAGE_FR_MEM_TYPE"=''INCLUDED_PARTY_USAGE'' AND ');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('              "PUFM"."PARTY_USAGE_ASG_SEL_CRTERIA"=''ACTIVE''))');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('   7 - access("PARTY_USAGE_FR_ID"=)');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('   9 - access("PARTY_USAGE_FR_CODE"=''ELIGIBLE_CUSTOMERS'')');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('  10 - filter(("PUA"."EFFECTIVE_END_DATE">SYSDATE@! AND "PUA"."STATUS_FLAG"=''A'' AND ');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('              "PUA"."EFFECTIVE_START_DATE"<=SYSDATE@!))');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('  11 - filter("PARTYPEO"."STATUS"=''A'')');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values (' ');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('Note');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('-----');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('   - Warning: basic plan statistics not available. These are only collected when:');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('       * hint ''gather_plan_statistics'' is used for the statement or');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values ('       * parameter ''statistics_level'' is set to ''ALL'', at session or system level');
Insert into EXPORT_TABLE (PLAN_TABLE_OUTPUT) values (' ');
